export const resData = [
  {
    id: "res_101",
    name: "Spice Garden",
    cuisines: ["North Indian", "Chinese"],
    rating: 4.3,
    reviewsCount: 1287,
    costForTwo: 600,
    deliveryTime: 32,
    isOpen: true,
    location: "Indiranagar, Bangalore",
    distanceKm: 2.1,
    offers: ["20% OFF up to ₹100"],
    veg: false,
    imageUrl: "https://source.unsplash.com/400x300/?indian-food",
    lastMileTravel: 1.8,
    serviceable: true,
    hasOnlinePayment: true,
  },
  {
    id: "res_102",
    name: "Green Bowl",
    cuisines: ["Healthy Food", "Salads"],
    rating: 4.6,
    reviewsCount: 842,
    costForTwo: 500,
    deliveryTime: 25,
    isOpen: true,
    location: "Koramangala, Bangalore",
    distanceKm: 3.4,
    offers: ["Free Delivery"],
    veg: true,
    imageUrl: "https://source.unsplash.com/400x300/?salad",
    lastMileTravel: 2.9,
    serviceable: true,
    hasOnlinePayment: true,
  },
  {
    id: "res_103",
    name: "Burger Hub",
    cuisines: ["Fast Food", "Burgers"],
    rating: 4.1,
    reviewsCount: 2104,
    costForTwo: 400,
    deliveryTime: 28,
    isOpen: false,
    location: "BTM Layout, Bangalore",
    distanceKm: 4.2,
    offers: ["Buy 1 Get 1"],
    veg: false,
    imageUrl: "https://source.unsplash.com/400x300/?burger",
    lastMileTravel: 3.7,
    serviceable: true,
    hasOnlinePayment: false,
  },
  {
    id: "res_104",
    name: "Dosa Corner",
    cuisines: ["South Indian"],
    rating: 4.5,
    reviewsCount: 980,
    costForTwo: 250,
    deliveryTime: 20,
    isOpen: true,
    location: "Jayanagar, Bangalore",
    distanceKm: 1.5,
    offers: ["10% OFF"],
    veg: true,
    imageUrl: "https://source.unsplash.com/400x300/?dosa",
    lastMileTravel: 1.2,
    serviceable: true,
    hasOnlinePayment: true,
  },
  {
    id: "res_105",
    name: "Tandoori Nights",
    cuisines: ["North Indian", "Mughlai"],
    rating: 4.2,
    reviewsCount: 1560,
    costForTwo: 800,
    deliveryTime: 35,
    isOpen: true,
    location: "HSR Layout, Bangalore",
    distanceKm: 5.1,
    offers: ["Flat ₹150 OFF"],
    veg: false,
    imageUrl: "https://source.unsplash.com/400x300/?tandoori",
    lastMileTravel: 4.6,
    serviceable: true,
    hasOnlinePayment: true,
  },

  // NEW ONES ↓

  {
    id: "res_106",
    name: "Pizza Fiesta",
    cuisines: ["Italian", "Pizza"],
    rating: 4.4,
    reviewsCount: 1890,
    costForTwo: 700,
    deliveryTime: 30,
    isOpen: true,
    location: "Whitefield, Bangalore",
    distanceKm: 6.2,
    offers: ["15% OFF"],
    veg: false,
    imageUrl: "https://source.unsplash.com/400x300/?pizza",
    lastMileTravel: 5.5,
    serviceable: true,
    hasOnlinePayment: true,
  },
  {
    id: "res_107",
    name: "Chai Junction",
    cuisines: ["Beverages", "Snacks"],
    rating: 4.0,
    reviewsCount: 620,
    costForTwo: 200,
    deliveryTime: 18,
    isOpen: true,
    location: "Marathahalli, Bangalore",
    distanceKm: 2.8,
    offers: ["₹50 OFF"],
    veg: true,
    imageUrl: "https://source.unsplash.com/400x300/?tea",
    lastMileTravel: 2.3,
    serviceable: true,
    hasOnlinePayment: false,
  },
  {
    id: "res_108",
    name: "Sushi World",
    cuisines: ["Japanese"],
    rating: 4.7,
    reviewsCount: 540,
    costForTwo: 1200,
    deliveryTime: 40,
    isOpen: true,
    location: "MG Road, Bangalore",
    distanceKm: 3.0,
    offers: ["10% Cashback"],
    veg: false,
    imageUrl: "https://source.unsplash.com/400x300/?sushi",
    lastMileTravel: 2.5,
    serviceable: true,
    hasOnlinePayment: true,
  },
  {
    id: "res_109",
    name: "Rolls Mania",
    cuisines: ["Street Food", "Rolls"],
    rating: 4.2,
    reviewsCount: 1330,
    costForTwo: 300,
    deliveryTime: 22,
    isOpen: true,
    location: "Electronic City, Bangalore",
    distanceKm: 7.5,
    offers: ["Buy 2 Get 1"],
    veg: false,
    imageUrl: "https://source.unsplash.com/400x300/?rolls",
    lastMileTravel: 6.8,
    serviceable: true,
    hasOnlinePayment: true,
  },
  {
    id: "res_110",
    name: "Sweet Cravings",
    cuisines: ["Desserts", "Bakery"],
    rating: 4.6,
    reviewsCount: 910,
    costForTwo: 350,
    deliveryTime: 24,
    isOpen: true,
    location: "Indiranagar, Bangalore",
    distanceKm: 2.0,
    offers: ["Free Dessert"],
    veg: true,
    imageUrl: "https://source.unsplash.com/400x300/?dessert",
    lastMileTravel: 1.6,
    serviceable: true,
    hasOnlinePayment: true,
  },
  {
    id: "res_111",
    name: "Biryani House",
    cuisines: ["Hyderabadi", "Biryani"],
    rating: 4.3,
    reviewsCount: 2500,
    costForTwo: 550,
    deliveryTime: 33,
    isOpen: true,
    location: "BTM Layout, Bangalore",
    distanceKm: 4.0,
    offers: ["₹100 OFF"],
    veg: false,
    imageUrl: "https://source.unsplash.com/400x300/?biryani",
    lastMileTravel: 3.5,
    serviceable: true,
    hasOnlinePayment: true,
  },
  {
    id: "res_112",
    name: "Cafe Mocha",
    cuisines: ["Cafe", "Continental"],
    rating: 4.1,
    reviewsCount: 760,
    costForTwo: 650,
    deliveryTime: 27,
    isOpen: false,
    location: "Koramangala, Bangalore",
    distanceKm: 3.2,
    offers: ["20% OFF"],
    veg: true,
    imageUrl: "https://source.unsplash.com/400x300/?coffee",
    lastMileTravel: 2.7,
    serviceable: true,
    hasOnlinePayment: true,
  },
  {
    id: "res_113",
    name: "Kebab Express",
    cuisines: ["Mughlai", "Kebabs"],
    rating: 4.4,
    reviewsCount: 1450,
    costForTwo: 750,
    deliveryTime: 34,
    isOpen: true,
    location: "HSR Layout, Bangalore",
    distanceKm: 5.3,
    offers: ["Flat ₹120 OFF"],
    veg: false,
    imageUrl: "https://source.unsplash.com/400x300/?kebab",
    lastMileTravel: 4.7,
    serviceable: true,
    hasOnlinePayment: true,
  },
  {
    id: "res_114",
    name: "Pasta Street",
    cuisines: ["Italian", "Pasta"],
    rating: 4.5,
    reviewsCount: 880,
    costForTwo: 700,
    deliveryTime: 29,
    isOpen: true,
    location: "Whitefield, Bangalore",
    distanceKm: 6.0,
    offers: ["15% OFF"],
    veg: true,
    imageUrl: "https://source.unsplash.com/400x300/?pasta",
    lastMileTravel: 5.2,
    serviceable: true,
    hasOnlinePayment: true,
  },
  {
    id: "res_115",
    name: "The Juice Bar",
    cuisines: ["Beverages", "Juices"],
    rating: 4.2,
    reviewsCount: 500,
    costForTwo: 250,
    deliveryTime: 19,
    isOpen: true,
    location: "Jayanagar, Bangalore",
    distanceKm: 1.7,
    offers: ["Free Add-on"],
    veg: true,
    imageUrl: "https://source.unsplash.com/400x300/?juice",
    lastMileTravel: 1.3,
    serviceable: true,
    hasOnlinePayment: false,
  },
];